name: ZETTA

# Controls when the workflow will run
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!	
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'http://autanbr.com/dev'
    needs: build
    steps:
      - name: Run a one-line script2
        run: echo desenvolvimento
  deploy-hmg:
      runs-on: ubuntu-latest
      environment:
        name: hmg
        url: 'http://autanbr.com/hmg'

      needs: deploy-dev
      steps:
        - name: Run a one-line script2
          run: echo desenvolvimento	
  deploy-prd:
        runs-on: ubuntu-latest
        environment:
          name: prd
          url: 'http://autanbr.com/prd'

        needs: deploy-hmg
        steps:
          - name: Run a one-line script2
            run: echo desenvolvimento

