name: ZETTA

# Controls when the workflow will run
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!



deploy-dev:
  runs-on: ubuntu-latest
  enviroment:
    name: dev
    url: 'autanbr.com.br'
  needs: build
  steps:
    - name: Run a one-line script
      run: echo desenvolvimento
  

deploy-hmg:
  runs-on: ubuntu-latest
  enviroment:
    name: dev
    url: 'autanbr.com.br'
  needs: deploy-dev
  steps:
    - name: Run a one-line script
      run: echo homologacao
      
      
deploy-prd:
  runs-on: ubuntu-latest
  enviroment:
    name: dev
    url: 'autanbr.com.br'
  needs: deploy-hmg
  steps:
    - name: Run a one-line script
      run: echo producao

